[2024-12-21T21:39:02.951+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: commiteando_cosas.commit_and_push_task scheduled__2024-12-21T21:38:00+00:00 [queued]>
[2024-12-21T21:39:02.958+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: commiteando_cosas.commit_and_push_task scheduled__2024-12-21T21:38:00+00:00 [queued]>
[2024-12-21T21:39:02.959+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-12-21T21:39:02.959+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2024-12-21T21:39:02.959+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-12-21T21:39:02.970+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): commit_and_push_task> on 2024-12-21 21:38:00+00:00
[2024-12-21T21:39:02.973+0000] {standard_task_runner.py:55} INFO - Started process 8804 to run task
[2024-12-21T21:39:02.977+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'commiteando_cosas', 'commit_and_push_task', 'scheduled__2024-12-21T21:38:00+00:00', '--job-id', '2667', '--raw', '--subdir', 'DAGS_FOLDER/elPataCommits.py', '--cfg-path', '/tmp/tmpd9hw9moy']
[2024-12-21T21:39:02.978+0000] {standard_task_runner.py:83} INFO - Job 2667: Subtask commit_and_push_task
[2024-12-21T21:39:03.027+0000] {task_command.py:376} INFO - Running <TaskInstance: commiteando_cosas.commit_and_push_task scheduled__2024-12-21T21:38:00+00:00 [running]> on host a39b43f32cb0
[2024-12-21T21:39:03.083+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=commiteando_cosas
AIRFLOW_CTX_TASK_ID=commit_and_push_task
AIRFLOW_CTX_EXECUTION_DATE=2024-12-21T21:38:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-12-21T21:38:00+00:00
[2024-12-21T21:39:03.084+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-12-21T21:39:03.084+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n        git add . &&\n        git commit -m "Commit diario: $(date \'+%Y-%m\')" &&\n        git push origin main\n        ']
[2024-12-21T21:39:03.091+0000] {subprocess.py:86} INFO - Output:
[2024-12-21T21:39:03.095+0000] {subprocess.py:93} INFO - fatal: not a git repository (or any of the parent directories): .git
[2024-12-21T21:39:03.095+0000] {subprocess.py:97} INFO - Command exited with return code 128
[2024-12-21T21:39:03.104+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 128.
[2024-12-21T21:39:03.107+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=commiteando_cosas, task_id=commit_and_push_task, execution_date=20241221T213800, start_date=20241221T213902, end_date=20241221T213903
[2024-12-21T21:39:03.116+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 2667 for task commit_and_push_task (Bash command failed. The command returned a non-zero exit code 128.; 8804)
[2024-12-21T21:39:03.161+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2024-12-21T21:39:03.175+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
