[2024-12-21T22:18:03.978+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: commiteando_cosas.commit_and_push_task scheduled__2024-12-21T22:17:00+00:00 [queued]>
[2024-12-21T22:18:03.986+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: commiteando_cosas.commit_and_push_task scheduled__2024-12-21T22:17:00+00:00 [queued]>
[2024-12-21T22:18:03.986+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-12-21T22:18:03.987+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2024-12-21T22:18:03.987+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-12-21T22:18:03.997+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): commit_and_push_task> on 2024-12-21 22:17:00+00:00
[2024-12-21T22:18:04.000+0000] {standard_task_runner.py:55} INFO - Started process 11057 to run task
[2024-12-21T22:18:04.003+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'commiteando_cosas', 'commit_and_push_task', 'scheduled__2024-12-21T22:17:00+00:00', '--job-id', '2784', '--raw', '--subdir', 'DAGS_FOLDER/elPataCommits.py', '--cfg-path', '/tmp/tmp8z6_1okr']
[2024-12-21T22:18:04.003+0000] {standard_task_runner.py:83} INFO - Job 2784: Subtask commit_and_push_task
[2024-12-21T22:18:04.049+0000] {task_command.py:376} INFO - Running <TaskInstance: commiteando_cosas.commit_and_push_task scheduled__2024-12-21T22:17:00+00:00 [running]> on host a39b43f32cb0
[2024-12-21T22:18:04.103+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=commiteando_cosas
AIRFLOW_CTX_TASK_ID=commit_and_push_task
AIRFLOW_CTX_EXECUTION_DATE=2024-12-21T22:17:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-12-21T22:17:00+00:00
[2024-12-21T22:18:04.103+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-12-21T22:18:04.104+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n        git add . &&\n        git commit -m "Commit diario: $(date \'+%Y-%m\')" &&\n        git push origin main\n        ']
[2024-12-21T22:18:04.112+0000] {subprocess.py:86} INFO - Output:
[2024-12-21T22:18:04.115+0000] {subprocess.py:93} INFO - fatal: not a git repository (or any of the parent directories): .git
[2024-12-21T22:18:04.116+0000] {subprocess.py:97} INFO - Command exited with return code 128
[2024-12-21T22:18:04.124+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 128.
[2024-12-21T22:18:04.127+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=commiteando_cosas, task_id=commit_and_push_task, execution_date=20241221T221700, start_date=20241221T221803, end_date=20241221T221804
[2024-12-21T22:18:04.138+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 2784 for task commit_and_push_task (Bash command failed. The command returned a non-zero exit code 128.; 11057)
[2024-12-21T22:18:04.184+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2024-12-21T22:18:04.198+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
