[2024-12-21T22:13:10.709+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: commiteando_cosas.commit_and_push_task scheduled__2024-12-21T22:12:00+00:00 [queued]>
[2024-12-21T22:13:10.717+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: commiteando_cosas.commit_and_push_task scheduled__2024-12-21T22:12:00+00:00 [queued]>
[2024-12-21T22:13:10.717+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-12-21T22:13:10.717+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2024-12-21T22:13:10.717+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-12-21T22:13:10.732+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): commit_and_push_task> on 2024-12-21 22:12:00+00:00
[2024-12-21T22:13:10.735+0000] {standard_task_runner.py:55} INFO - Started process 10773 to run task
[2024-12-21T22:13:10.739+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'commiteando_cosas', 'commit_and_push_task', 'scheduled__2024-12-21T22:12:00+00:00', '--job-id', '2769', '--raw', '--subdir', 'DAGS_FOLDER/elPataCommits.py', '--cfg-path', '/tmp/tmpyqzmlm8p']
[2024-12-21T22:13:10.740+0000] {standard_task_runner.py:83} INFO - Job 2769: Subtask commit_and_push_task
[2024-12-21T22:13:10.785+0000] {task_command.py:376} INFO - Running <TaskInstance: commiteando_cosas.commit_and_push_task scheduled__2024-12-21T22:12:00+00:00 [running]> on host a39b43f32cb0
[2024-12-21T22:13:10.841+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=commiteando_cosas
AIRFLOW_CTX_TASK_ID=commit_and_push_task
AIRFLOW_CTX_EXECUTION_DATE=2024-12-21T22:12:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-12-21T22:12:00+00:00
[2024-12-21T22:13:10.842+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-12-21T22:13:10.843+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n        git add . &&\n        git commit -m "Commit diario: $(date \'+%Y-%m\')" &&\n        git push origin main\n        ']
[2024-12-21T22:13:10.850+0000] {subprocess.py:86} INFO - Output:
[2024-12-21T22:13:10.854+0000] {subprocess.py:93} INFO - fatal: not a git repository (or any of the parent directories): .git
[2024-12-21T22:13:10.854+0000] {subprocess.py:97} INFO - Command exited with return code 128
[2024-12-21T22:13:10.867+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 128.
[2024-12-21T22:13:10.871+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=commiteando_cosas, task_id=commit_and_push_task, execution_date=20241221T221200, start_date=20241221T221310, end_date=20241221T221310
[2024-12-21T22:13:10.882+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 2769 for task commit_and_push_task (Bash command failed. The command returned a non-zero exit code 128.; 10773)
[2024-12-21T22:13:10.924+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2024-12-21T22:13:10.939+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
